
import {Sidebar, SideBarInfo} from "sidebar.slint";
import {SearchBar} from "searchbar.slint";
import {Home, Search, Playlists, Settings, SearchScreen} from "screens/screens.slint";
import { TabWidget , VerticalBox} from "std-widgets.slint";

export { SearchScreen, SideBarInfo }

export component App inherits Window {
    preferred-width: 640px;
    preferred-height: 480px;

    callback skip_back <=> sidebar.skip_back;
    callback play_pause <=> sidebar.play_pause;
    callback skip_forward <=> sidebar.skip_forward;

    callback searched <=> search_bar.accepted;

    in property <string> name;
    in-out property <string> song-title <=> sidebar.song-title;
    in-out property <image> cover_art <=> sidebar.cover_art;
    in property <bool> is-paused <=> sidebar.is-paused;
    title <=> name;
    in property <string> song-time <=> sidebar.time;



    HorizontalLayout {

        sidebar := Sidebar {}

        VerticalLayout {
            search_bar := SearchBar{}

            if (search-bar.current-item == 0) : Home {}
            if (search-bar.current-item == 1) : Search {}
            if (search-bar.current-item == 2) : Playlists {}
            if (search-bar.current-item == 3) : Settings {}

        }          

        



    }


}