import { ProgressIndicator } from "std-widgets.slint";

component MediaButton inherits TouchArea {

    in property <image> image-url;
    width: 30px;
    height: 30px;
    Rectangle {
        width: 35px;
        height: 35px;
        border-radius: 6px;
        background: root.has-hover ? #8b8b8b : #1b1b1b;

        animate background {
             duration: 100ms;
        }
    }
    icon := Image {
        width: 20px;
        height: 20px;
        source: image-url;
    }

}

export component Sidebar inherits Rectangle {
    width: 180px;
    background: #1b1b1b;

    callback skip_back <=> skip_back.clicked;
    callback play_pause <=> play.clicked;
    callback skip_forward <=> skip_forward.clicked;

    in-out property <string> song-title <=> title.text;
    in-out property <image> cover_art <=> cover.source;
    in property <bool> is-paused;
    in property <string> time;


    VerticalLayout {
        alignment: start;
        padding-top: 15px;
        padding-bottom: 30px;
        spacing: 10px;
        padding-left: 30px;
        padding-right: 30px;
        art := Rectangle {   
            width: 120px;
            height: 120px;
            border-width: 1px;
            border-color: #3f3f3f;
            cover := Image {
                height: 120px;
                width: 120px;
                source: @image-url("");
            }
        }

        title := Text {
            horizontal-alignment: center;
            font-size: 16px;
        }

        media_controls := Rectangle {


            HorizontalLayout {
                alignment: space-around;

                skip_forward := MediaButton {

                    image-url: @image-url("img/skip_back.png");
                }
                play := MediaButton {
                    image-url: is-paused ? @image-url("img/play.png") : @image-url("img/pause.png");
                }
                skip_back := MediaButton {
                    image-url: @image-url("img/skip_forward.png");
                }
            }

        }
    }
}

export global SideBarInfo {
    in property <percent> progress_bar;
}



